name: assign_review_by_comment by issue_comment
on: [issue_comment]

jobs:
  assign_review_by_comment:
    runs-on: ubuntu-latest
    steps:
      - name: assign_review_by_comment
        uses: taha-husain/github-action-auto-assign@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ONLY_REVIEWERS: true
